### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by jaylinski** [yahoo/yfuzz#29]
I noticed the last commit was pushed in 2018. Is this project still in development?

**Comment by ian-fox** [comment]
Originally this was intended to reproduce some of the functionality of [Clusterfuzz](https://github.com/google/clusterfuzz) which was not (at that time) open-sourced. Since then Google has released more of that project to the internet, and there is no longer a need for this project.

**Comment by jaylinski** [comment]
Thanks for the clarification!
